version: '3.9'
services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pa55w0rd2019"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  dotnet:
    build: 
      context: .
      dockerfile: dotnet.Dockerfile
    ports:
      - "5000:5000"