version: '3.9'
services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pa55w0rd2019"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  dotnet:
    build:
      context: .
      dockerfile: dotnet.Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - ms-sql-server
    restart: "always"
  node:
    build:
      context: .
      dockerfile: node.Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - dotnet
  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - node